name: "shop-backend"
mode: "dev"
port: 9090
version: "v0.1.0"
start_time: "2022-10-12"
machine_id: 1

user:
  width: 4 # 手机验证码位数
  min_pass_len: 8
  max_pass_len: 15

log:
  level: "debug"
  fileName: "shop-backend.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "shop"
  max_open_conns: 20
  max_idel_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

aliyun:
  access_key_id: "#"
  access_key_secret: "#"
  oss:
    endpoint: "https://oss-cn-zhangjiakou.aliyuncs.com"
    bucket_name: "llshop-project"
    user_avatar_prefix: "shop/user/avatar/"
