basePath: /api/v1
definitions:
  models.ParamSignUp:
    properties:
      code:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - code
    - password
    - phone
    type: object
host: y8ccqm.natappfree.cc
info:
  contact: {}
  description: llShop后端接口API
  license:
    name: Apache 2.0
  termsOfService: https://github.com/mayooot/llShop-backend
  title: llShop-backend
  version: "1.0"
paths:
  /phone:
    get:
      description: 前端传递11位手机号，后端随机生成4位验证码。存入Redis，并异步调用阿里云SMS服务发送验证码。
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取验证码
      tags:
      - 用户相关接口
  /signup:
    post:
      description: 前端传递JSON类型对象，后端完成校验后注册新用户。
      parameters:
      - description: 验证码
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.ParamSignUp'
      produces:
      - application/json
      responses: {}
      summary: 注册用户
      tags:
      - 用户相关接口
swagger: "2.0"
